# Generated by Django 4.1.3 on 2022-11-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esieechat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='idConversation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='esieechat.conversation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convutilisateur',
            name='idUtilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
