# Generated by Django 4.1.3 on 2022-11-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esieechat', '0002_message_idconversation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convutilisateur',
            old_name='idConversation',
            new_name='id_conversation',
        ),
        migrations.RenameField(
            model_name='convutilisateur',
            old_name='idUtilisateur',
            new_name='id_utilisateur',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='dateHeure',
            new_name='date_heure',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='idConversation',
            new_name='id_conversation',
        ),
    ]
