# Generated by Django 4.1.3 on 2022-11-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esieechat', '0003_rename_idconversation_convutilisateur_id_conversation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convutilisateur',
            old_name='id_conversation',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='convutilisateur',
            old_name='id_utilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id_conversation',
            new_name='conversation',
        ),
    ]
