# Generated by Django 4.1.3 on 2022-11-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esieechat', '0005_alter_conversation_nom_alter_message_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(max_length=125),
        ),
    ]
