# Generated by Django 4.1.3 on 2022-11-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TimeField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.DateField(auto_now=True)),
                ('annee_fin', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFiliere', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='esieeverse.filiere')),
                ('idPromotion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='esieeverse.promotion')),
            ],
        ),
    ]
