# Generated by Django 4.1.3 on 2023-04-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='nom',
            field=models.CharField(max_length=4),
        ),
    ]
