# Generated by Django 4.1.3 on 2022-11-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filpromo',
            old_name='idFiliere',
            new_name='id_filiere',
        ),
        migrations.RenameField(
            model_name='filpromo',
            old_name='idPromotion',
            new_name='id_promotion',
        ),
    ]
