# Generated by Django 4.1.3 on 2022-11-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0002_rename_idfiliere_filpromo_id_filiere_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filpromo',
            old_name='id_filiere',
            new_name='filiere',
        ),
        migrations.RenameField(
            model_name='filpromo',
            old_name='id_promotion',
            new_name='promotion',
        ),
    ]
