# Generated by Django 4.1.3 on 2022-12-08 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0002_alter_promotion_annee_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='annee_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='annee_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
