# Generated by Django 4.1.3 on 2022-11-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0003_rename_id_filiere_filpromo_filiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=3),
        ),
    ]
