# Generated by Django 4.1.3 on 2022-12-08 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0003_alter_promotion_annee_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='annee_debut',
            field=models.PositiveSmallIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='annee_fin',
            field=models.PositiveSmallIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
