# Generated by Django 4.1.3 on 2023-01-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0004_alter_promotion_annee_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='annee_debut',
        ),
    ]
