# Generated by Django 4.1.3 on 2023-02-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0005_remove_promotion_annee_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo_de_profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
