# Generated by Django 4.1.3 on 2023-02-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0006_utilisateur_photo_de_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_de_profile',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
