# Generated by Django 4.1.3 on 2022-12-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=125)),
                ('date', models.DateTimeField(auto_now=True)),
                ('contien_multimedia', models.BooleanField(default=False)),
                ('nb_likes', models.PositiveSmallIntegerField(default=0)),
                ('nb_dislikes', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.publication')),
                ('date_debut', models.DateTimeField(auto_now=True)),
                ('date_fin', models.DateTimeField()),
            ],
            bases=('publication.publication',),
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.evenement')),
            ],
        ),
    ]
