# Generated by Django 4.1.3 on 2023-02-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esieeverse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=125)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, blank=True, upload_to='media/')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes_utilisateur', to='esieeverse.utilisateur')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_utilisateur', to='esieeverse.utilisateur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esieeverse.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publication.publication')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
            ],
            bases=('publication.publication',),
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esieeverse.utilisateur')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.evenement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='choix',
            constraint=models.UniqueConstraint(fields=('id', 'evenement', 'utilisateur'), name='unique_vote_user'),
        ),
    ]
