# Generated by Django 4.1.3 on 2023-04-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
