# Generated by Django 4.1.3 on 2023-01-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choix',
            name='nb_choisis',
            field=models.IntegerField(default=0),
        ),
    ]
