# Generated by Django 4.1.3 on 2023-03-06 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0001_initial'),
        ('publication', '0002_remove_publication_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='auteur',
            field=models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='esieeverse.utilisateur'),
        ),
    ]
