# Generated by Django 4.1.3 on 2023-04-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_publication_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.AddField(
            model_name='publication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
