# Generated by Django 4.1.3 on 2023-01-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_choix_nb_choisis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='contien_multimedia',
            new_name='contient_multimedia',
        ),
    ]
