# Generated by Django 4.1.3 on 2023-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_rename_contien_multimedia_publication_contient_multimedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='date_debut',
            field=models.DateTimeField(),
        ),
    ]
