# Generated by Django 4.1.3 on 2023-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_remove_publication_image_publication_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='image',
        ),
        migrations.AddField(
            model_name='evenement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
