# Generated by Django 4.1.3 on 2023-05-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_remove_evenement_image_evenement_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choix',
            name='nom',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
