# Generated by Django 4.1.3 on 2023-02-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0006_utilisateur_photo_de_profile'),
        ('publication', '0005_publication_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='contient_multimedia',
        ),
        migrations.AddField(
            model_name='choix',
            name='utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='esieeverse.utilisateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddConstraint(
            model_name='choix',
            constraint=models.UniqueConstraint(fields=('evenement', 'utilisateur'), name='unique_user'),
        ),
    ]
