# Generated by Django 4.1.3 on 2023-02-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0007_alter_utilisateur_photo_de_profile'),
        ('publication', '0007_remove_choix_unique_user_choix_unique_vote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='nb_dislikes',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='nb_likes',
        ),
        migrations.AddField(
            model_name='publication',
            name='dislike',
            field=models.ManyToManyField(related_name='dislike_utilisateurs', to='esieeverse.utilisateur'),
        ),
        migrations.AddField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(related_name='like_utilisateurs', to='esieeverse.utilisateur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
