# Generated by Django 4.1.3 on 2023-02-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esieeverse', '0007_alter_utilisateur_photo_de_profile'),
        ('publication', '0008_remove_publication_nb_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='dislike',
        ),
        migrations.AddField(
            model_name='publication',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes_utilisateur', to='esieeverse.utilisateur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(related_name='likes_utilisateur', to='esieeverse.utilisateur'),
        ),
    ]
