# Generated by Django 4.1.3 on 2023-02-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0010_alter_publication_dislikes_alter_publication_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choix',
            name='nb_choisis',
        ),
    ]
